Global:
  model: PP-DocLayoutV3
  mode: train
  dataset_dir: "data/dense_chem"
  device: gpu:0
  output: "output/ppdoclayoutv3_ft"

CheckDataset:
  convert:
    enable: False
    src_dataset_type: null
  split:
    enable: False
    train_percent: null
    val_percent: null

Train:
  num_classes: 26
  epochs_iters: 50
  batch_size: 4
  learning_rate: 0.0001
  pretrain_weight_path: https://paddle-model-ecology.bj.bcebos.com/paddlex/official_pretrained_model/PP-DocLayoutV3_pretrained.pdparams
  warmup_steps: 100
  resume_path: null
  log_interval: 10
  eval_interval: 1

Evaluate:
  weight_path: "output/ppdoclayoutv3_ft/best_model/best_model.pdparams"
  log_interval: 10

Export:
  weight_path: "output/ppdoclayoutv3_ft/best_model/best_model.pdparams"

Predict:
  batch_size: 1
  model_dir: "output/ppdoclayoutv3_ft/inference"
  input: null
  kernel_option:
    run_mode: paddle
